function loadCaches(){students=[];for(let r=6;r<=254;r++){const nama=trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'C'+r));if(!nama)continue;students.push({source:'Siswa',row:r,id:getStudentId(r),name:nama,gender:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'D'+r)),kelas:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'G'+r)),program:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'H'+r)),parent:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'K'+r)),parentPhone:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'L'+r)),yearMasuk:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'N'+r)),belt:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'O'+r)),memberStatus:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'P'+r)),studentStatus:trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'Q'+r))})}}
function loadPengurusPeople(){pengurusPeople=[];for(let r=6;r<=505;r++){const name=trim(cellText(docs['Data Pengurus'],cellMaps['Data Pengurus'],'C'+r));if(!name)continue;pengurusPeople.push({source:'Pengurus',row:r,id:getPengurusId(r),name,gender:trim(cellText(docs['Data Pengurus'],cellMaps['Data Pengurus'],'D'+r)),position:trim(cellText(docs['Data Pengurus'],cellMaps['Data Pengurus'],'E'+r)),status:trim(cellText(docs['Data Pengurus'],cellMaps['Data Pengurus'],'J'+r))})}}
function loadAttendanceMonths(){attendanceMonths=[];for(let c=5;c<=220;c+=6){const n=trim(cellText(docs['Kehadiran'],cellMaps['Kehadiran'],ref(c,2)));if(n)attendanceMonths.push({name:n,start:c})}const dd=$('attMonth');dd.innerHTML='';for(let i=0;i<attendanceMonths.length;i++){const o=document.createElement('option');o.value=i;o.textContent=attendanceMonths[i].name;dd.appendChild(o)}}
function countRows(sheet,start,end,col){let n=0;for(let r=start;r<=end;r++)if(trim(cellText(docs[sheet],cellMaps[sheet],col+r)))n++;return n}
function refreshDashboard(){if(!docs['Data Siswa'])return;$('mSiswa').textContent=students.length;$('mAktif').textContent=students.filter(s=>s.memberStatus==='Anggota Aktif').length;$('mAlumni').textContent=countRows('Data Alumni',6,505,'C');$('mPengurus').textContent=pengurusPeople.length;$('mPrestasi').textContent=countRows('Prestasi',5,504,'C');$('mKeluar').textContent=countRows('Data Keluar',6,300,'E')}

async function prepareWorkbook(bytes,name){setStatus('Membaca struktur database Pagar Nusa...');zipEntries=await readZip(bytes);entryMap=new Map(zipEntries.map(e=>[e.name,e]));for(const n of ['xl/workbook.xml','xl/_rels/workbook.xml.rels'])if(!entryMap.has(n))throw new Error('Struktur workbook tidak lengkap: '+n);const wbDoc=parseXML(bytesToText(entryMap.get('xl/workbook.xml').data)),rels=parseXML(bytesToText(entryMap.get('xl/_rels/workbook.xml.rels').data));const relMap={};for(const r of allLocal(rels,'Relationship'))relMap[r.getAttribute('Id')]=normalizeRelTarget(r.getAttribute('Target'));sheetPaths={};for(const s of allLocal(wbDoc,'sheet')){const id=attrLocal(s,'id');sheetPaths[s.getAttribute('name')]=relMap[id]}const required=['Referensi','Data Siswa','Data Pengurus','Data Alumni','Kehadiran','Kenaikan Tingkat','Prestasi','Iuran','Data Pelanggaran','Data SP 1-3','Data Keluar'];for(const n of required)if(!sheetPaths[n]||!entryMap.has(sheetPaths[n]))throw new Error('Sheet wajib tidak ditemukan: '+n);sharedStrings=[];if(entryMap.has('xl/sharedStrings.xml')){const ss=parseXML(bytesToText(entryMap.get('xl/sharedStrings.xml').data));for(const si of allLocal(ss,'si'))sharedStrings.push(Array.from(si.getElementsByTagNameNS('*','t')).map(t=>t.textContent).join(''))}docs={};cellMaps={};for(const n of required){docs[n]=parseXML(bytesToText(entryMap.get(sheetPaths[n]).data));cellMaps[n]=buildCellMap(docs[n])}docs._workbook=wbDoc;dirtySheets.clear();loadCaches();loadPengurusPeople();loadAttendanceMonths();refreshDashboard();originalName=name||'Database_Pagar_Nusa_BROWSER.xlsm';$('dbName').textContent=originalName;dirty=false;selectedRow=0;selectedPerson=null;switchModule(activeModule);setStatus('Database siap digunakan. Pilih menu input di sebelah kiri.','ok')}
async function chooseDatabase(){if('showOpenFilePicker'in window){try{const h=await window.showOpenFilePicker({multiple:false,types:[{description:'Database Pagar Nusa',accept:{'application/vnd.ms-excel.sheet.macroEnabled.12':['.xlsm'],'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx']}}]});if(!h||!h.length)return;fileHandle=h[0];let perm='granted';try{if(fileHandle.queryPermission)perm=await fileHandle.queryPermission({mode:'readwrite'});if(perm!=='granted'&&fileHandle.requestPermission)perm=await fileHandle.requestPermission({mode:'readwrite'})}catch(_){perm='prompt'}const f=await fileHandle.getFile();const raw=await f.arrayBuffer();await prepareWorkbook(raw,f.name);autosaveMode=perm==='granted';await cacheDatabase(raw,f.name,fileHandle,autosaveMode);$('saveMode').textContent=autosaveMode?'AUTOSAVE AKTIF':'DATABASE DIINGAT';$('saveMode').className='badge ok';setStatus(autosaveMode?'Database siap — <b>AUTOSAVE AKTIF</b>. Database juga diingat untuk refresh/buka ulang.':'Database siap dan <b>DIINGAT</b> browser. Tidak perlu upload ulang setelah refresh/buka ulang; perubahan tersimpan di browser sampai file final disimpan.','ok');return}catch(e){if(e&&e.name==='AbortError')return;console.warn(e)}}$('file').click()}
async function loadSelectedFile(file){if(!file)return;try{fileHandle=null;autosaveMode=false;const raw=await file.arrayBuffer();await prepareWorkbook(raw,file.name);await cacheDatabase(raw,file.name,null,false);$('saveMode').textContent='DATABASE DIINGAT';$('saveMode').className='badge ok';setStatus('Database siap dan <b>DIINGAT</b> browser. Setelah refresh atau HTML dibuka kembali, database dimuat otomatis tanpa upload ulang.','ok')}catch(e){console.error(e);setStatus('Gagal membuka database: <b>'+esc(e.message)+'</b>','err')}}

function switchModule(k){activeModule=k;selectedRow=0;selectedPerson=null;renderNav();const m=modules[k];$('moduleTitle').textContent=m.icon+' '+m.title;$('moduleIntro').textContent=m.intro;$('rowBadge').textContent='DATA BARU';$('rowBadge').className='badge';$('personSection').className=m.link?'':'hidden';$('attendanceSection').className=m.special==='attendance'?'':'hidden';$('formSection').className=m.special==='attendance'?'hidden':'';$('personResults').innerHTML='';$('personSearch').value='';$('personCard').className='personCard hidden';if(m.link){$('personLabel').textContent=m.link==='both'?'Cari siswa/anggota/pengurus':'Cari siswa / anggota';searchPeople()}if(m.special!=='attendance')renderForm();else{clearAttendanceInputs();loadAttendanceCurrent()}$('recordSearch').value='';renderRecords(false);window.dispatchEvent(new CustomEvent('pn:module-open',{detail:{module:k,sheet:m.sheet}}))}
function renderForm(){const m=modules[activeModule],box=$('formGrid');box.innerHTML='';for(const f of m.fields||[]){const wrap=document.createElement('div');wrap.className='field '+(f.cls||'');const lab=document.createElement('label');lab.textContent=f.l+(f.req?' *':'');wrap.appendChild(lab);let el;if(f.type==='textarea'){el=document.createElement('textarea')}else if(f.type==='select'){el=document.createElement('select');const blank=document.createElement('option');blank.value='';blank.textContent='— pilih —';el.appendChild(blank);const opts=f.ref?getRefOptions(f.ref):(f.opts||[]);for(const v of opts){const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)}}else{el=document.createElement('input');el.type=f.type==='date'?'date':f.type==='number'?'number':'text';if(f.min!==undefined)el.min=f.min;if(f.max!==undefined)el.max=f.max}el.id='f_'+f.c;el.className='yellow';wrap.appendChild(el);box.appendChild(wrap)}}
function getFieldValue(f){const el=$('f_'+f.c);if(!el)return '';return trim(el.value)}
function setFieldValue(f,v){const el=$('f_'+f.c);if(!el)return;if(f.type==='date')el.value=excelToISO(v);else el.value=v??''}
function clearFormFields(){const m=modules[activeModule];for(const f of m.fields||[])setFieldValue(f,'')}
function validateForm(){const m=modules[activeModule];for(const f of m.fields||[]){const v=getFieldValue(f);if(f.req&&!v){alert('Field wajib belum diisi: '+f.l);$('f_'+f.c).focus();return false}if(f.type==='number'&&v){const n=Number(v);if(!Number.isFinite(n)||(f.min!==undefined&&n<f.min)||(f.max!==undefined&&n>f.max)){alert('Nilai tidak valid: '+f.l);return false}}}return true}
function firstBlankRow(m){for(let r=m.start;r<=m.end;r++)if(!trim(cellText(docs[m.sheet],cellMaps[m.sheet],m.primary+r)))return r;return 0}
function styleAddr(m,col){return col+m.start}
function writeFields(m,row){for(const f of m.fields||[]){let v=getFieldValue(f),num=f.type==='number'||f.type==='date';if(f.type==='date')v=v?isoToExcel(v):'';writeOrCache(m.sheet,f.c+row,v,num,styleAddr(m,f.c))}}
function clearRowFields(m,row){for(const f of m.fields||[])clearCell(m.sheet,f.c+row,true)}
function personStatus(p){if(!p)return'';if(p.source==='Pengurus')return p.status||p.position||'';return [p.memberStatus,p.studentStatus].filter(Boolean).join(' / ')}
